---
- name: reload nginx
  ansible.builtin.command:
    argv:
      - nginx
      - -s
      - reload

- name: restart nginx
  ansible.builtin.command:
    argv:
      - systemctl
      - restart
      - nginx
